# Generated by Django 2.1.15 on 2021-05-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_handbook', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('surname', models.CharField(max_length=70)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=12)),
                ('ufrg', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=30)),
                ('cellphone', models.CharField(max_length=14)),
                ('telephone', models.CharField(max_length=9)),
                ('medical_insurance', models.CharField(max_length=70)),
                ('card_number', models.IntegerField()),
                ('card_validity', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Registers',
            },
        ),
    ]
