# Generated by Django 2.1.15 on 2021-05-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210504_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact_way',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='newsletter',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cellphone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
    ]
