# Generated by Django 2.1.15 on 2021-05-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210505_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mediacal_Insurance',
            fields=[
                ('id_insurance', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Medical_Insurance',
                'verbose_name_plural': 'Medical_Insurance',
            },
        ),
    ]
