# Generated by Django 2.1.15 on 2021-05-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mediacal_insurance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mediacal_Insurance',
            new_name='Insurance',
        ),
    ]
